channel_sources:
- freecad/label/dev,conda-forge
channel_targets:
- Ondsel dev
MACOSX_SDK_VERSION:   # [osx]
  - '11.0'            # [osx]
c_stdlib_version:     # [osx]
  - '11.0'            # [osx and arm64]
  - '10.13'           # [osx and x86_64]